# Generated by Django 5.1.4 on 2024-12-31 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorprofile', '0002_category_doctorprofile_province_doctorprofile_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='image',
        ),
    ]
