# Generated by Django 5.1.4 on 2025-01-06 21:36

import django.db.models.deletion
from django.db import migrations, models

# class migrations
class Migration(migrations.Migration):

    dependencies = [
        ('consultationsystem', '0001_initial'),
        ('doctorprofile', '0001_initial'),
        ('patientfilesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingconsultation',
            old_name='timeslot',
            new_name='appointment_time',
        ),
        migrations.CreateModel(
            name='CallConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultationsystem.bookingconsultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorprofile.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientfilesystem.patient')),
            ],
        ),
    ]
