# Generated by Django 5.1.4 on 2024-12-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_doctorprofile_delete_doctorlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='doctor',
            new_name='user',
        ),
    ]
