# Generated by Django 5.1.4 on 2024-12-25 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_doctorprofile_category_and_more'),
        ('users', '0002_remove_doctorprofile_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('practice_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('services_offered', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('image', models.ImageField(upload_to='uploads/listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorListing',
        ),
    ]
